// Starter content: written into the database the first time it is set up, and
// shown on the public site if the database is ever unreachable.

import { MANAGER_SLUG } from '@/lib/constants'

export { MANAGER_SLUG }

export const practiceAreaSeed = [
  { slug: 'corporate-commercial-law', title: 'Corporate & Commercial Law', summary: 'From company formation to complex commercial transactions, we help Kenyan and international businesses structure, negotiate and protect their commercial interests.', heroImageUrl: 'https://images.pexels.com/photos/8428059/pexels-photo-8428059.jpeg?auto=compress&cs=tinysrgb&w=1000', content: 'Every engagement is led by an advocate who takes the time to understand your business model, not just the transaction in front of them.\n\n- Company Formation & Registration\n- Contract Drafting & Negotiation\n- Mergers & Acquisitions\n- Corporate Governance & Compliance\n- Commercial Finance & Payments\n- Data Protection Compliance', sortOrder: 1 },
  { slug: 'conveyancing-real-estate', title: 'Conveyancing & Real Estate', summary: 'Whether you are buying your first home, developing commercial property, or managing a real estate portfolio, our conveyancing team guides every transaction from offer to title transfer.', heroImageUrl: 'https://images.pexels.com/photos/7587880/pexels-photo-7587880.jpeg?auto=compress&cs=tinysrgb&w=1000', content: 'Property transactions in Kenya involve multiple registries, approvals and parties. We manage that process end-to-end so nothing falls through the cracks.\n\n- Sale & Purchase Agreements\n- Title Searches & Due Diligence\n- Transfer of Title\n- Lease Agreements\n- Land Subdivision & Development', sortOrder: 2 },
  { slug: 'dispute-resolution', title: 'Dispute Resolution', summary: 'Not every dispute needs to end up in court. We help clients resolve conflicts efficiently, through negotiation, mediation, arbitration, or litigation when necessary.', heroImageUrl: 'https://images.pexels.com/photos/7433830/pexels-photo-7433830.jpeg?auto=compress&cs=tinysrgb&w=1000', content: 'We assess every dispute on its merits and recommend the fastest, most cost-effective route to resolution, escalating to litigation only when it genuinely serves your interests.\n\n- Commercial Litigation\n- Negotiation & Mediation\n- Arbitration\n- Debt Recovery', sortOrder: 3 },
  { slug: 'family-succession-law', title: 'Family & Succession Law', summary: 'Family and succession matters are often deeply personal. We provide sensitive, practical guidance to help clients protect their families and their legacies.', heroImageUrl: 'https://images.pexels.com/photos/8441866/pexels-photo-8441866.jpeg?auto=compress&cs=tinysrgb&w=1000', content: 'We combine legal precision with genuine care, guiding families through decisions that matter for generations.\n\n- Wills & Estate Planning\n- Succession & Probate\n- Trusts\n- Matrimonial Property', sortOrder: 4 },
  { slug: 'employment-labour-law', title: 'Employment & Labour Law', summary: 'We advise both employers and employees on the full lifecycle of the employment relationship, from contracts and policies to disputes and terminations.', heroImageUrl: 'https://images.pexels.com/photos/6773652/pexels-photo-6773652.jpeg?auto=compress&cs=tinysrgb&w=1000', content: 'Our advice is practical and commercially minded, whether we are drafting policy or representing a party before the Employment and Labour Relations Court.\n\n- Contracts & Workplace Policies\n- Terminations & Redundancy\n- Employment Disputes\n- Compliance Audits', sortOrder: 5 },
  { slug: 'criminal-litigation', title: 'Criminal Litigation', summary: 'Facing criminal proceedings can be overwhelming. We provide firm, experienced representation at every stage, from arrest to appeal.', heroImageUrl: 'https://images.pexels.com/photos/5669619/pexels-photo-5669619.jpeg?auto=compress&cs=tinysrgb&w=1000', content: 'We protect our clients’ rights at every stage of criminal proceedings, from the first police interview through trial and, where necessary, appeal.\n\n- Bail Applications\n- Trial Representation\n- Appeals\n- White-Collar Defence', sortOrder: 6 },
]

export const teamMemberSeed = [
  { slug: MANAGER_SLUG, name: 'Harry Arunda', role: 'Manager', photoUrl: 'https://images.pexels.com/photos/32064778/pexels-photo-32064778.jpeg?auto=compress&cs=tinysrgb&w=800', tags: ['Firm Leadership', 'Corporate & Commercial Law', 'Dispute Resolution'], bio: `Long before his name was on the door, Harry Arunda was the person friends and family turned to when a letter from a bank, a landlord or a government office didn’t make sense. He noticed early how often ordinary people and growing businesses lost time, money and peace of mind simply because no one had explained the law to them in plain terms. That frustration became his calling.

He went on to study law at the University of Nairobi and was admitted as an Advocate of the High Court of Kenya. His early years in practice were spent in the thick of commercial transactions and hard-fought disputes, where he learned that the best legal outcome is the one that lets a client get back to running their business or their life, whether that is won in a boardroom or a courtroom.

Over more than a decade, Harry has advised companies, entrepreneurs and families across Kenya on complex commercial transactions, corporate governance and dispute resolution. Clients describe him as direct, calm under pressure and relentlessly practical. He is known for turning a thick file into a single clear recommendation.

Today, as Manager of Harry Advocates, he leads the firm’s day-to-day operations and sets the standard for how every matter is handled. He makes sure each client is heard, each deadline is met and each piece of advice is something the client can actually act on. He has built a team that shares that discipline, and he still takes a personal interest in the firm’s most important engagements.

Outside the office, Harry mentors young advocates entering the profession and is a firm believer that access to good counsel should never be a privilege. “People don’t come to us for legal theory,” he says. “They come to us because something important is at stake. Our job is to protect it.”`, education: 'LLB, University of Nairobi', barAdmission: 'Advocate of the High Court of Kenya', languages: 'English, Kiswahili', focusAreas: 'Firm Leadership, Corporate & Commercial, Dispute Resolution', email: 'info@harryadvocates.co.ke', sortOrder: 1 },
  { slug: 'grace-wanjiru', name: 'Grace Wanjiru', role: 'Partner, Family & Succession', photoUrl: 'https://images.pexels.com/photos/8312669/pexels-photo-8312669.jpeg?auto=compress&cs=tinysrgb&w=800', tags: ['Family & Succession Law', 'Trusts', 'Estate Planning'], bio: "Grace leads the firm's Family & Succession practice, guiding clients through some of the most personal and sensitive matters they will face.\n\nShe has particular experience in succession planning, estate administration and matrimonial property disputes, and is valued by clients for her patience, discretion and clear communication.", education: 'LLB, Kenyatta University', barAdmission: 'Advocate of the High Court of Kenya', languages: 'English, Kiswahili', focusAreas: 'Family & Succession, Trusts', email: 'info@harryadvocates.co.ke', sortOrder: 2 },
  { slug: 'michael-kiprotich', name: 'Michael Kiprotich', role: 'Senior Associate, Corporate & Commercial', photoUrl: 'https://images.pexels.com/photos/33844626/pexels-photo-33844626.jpeg?auto=compress&cs=tinysrgb&w=800', tags: ['Corporate & Commercial Law', 'Conveyancing & Real Estate'], bio: "Michael supports the firm's corporate and real estate practice, working closely with businesses and property developers on transactions, due diligence and regulatory compliance.\n\nHe has a keen interest in how digital payment systems, including mobile money, intersect with commercial law in Kenya.", education: 'LLB, Moi University', barAdmission: 'Advocate of the High Court of Kenya', languages: 'English, Kiswahili', focusAreas: 'Corporate & Commercial, Conveyancing', email: 'info@harryadvocates.co.ke', sortOrder: 3 },
  { slug: 'amina-hassan', name: 'Amina Hassan', role: 'Associate, Dispute Resolution', photoUrl: 'https://images.pexels.com/photos/3869642/pexels-photo-3869642.jpeg?auto=compress&cs=tinysrgb&w=800', tags: ['Dispute Resolution', 'Employment & Labour Law'], bio: 'Amina represents clients in commercial disputes, negotiations and proceedings before the Employment and Labour Relations Court.\n\nShe takes a pragmatic approach to conflict, working to find efficient resolutions wherever possible while preparing thoroughly for litigation when it becomes necessary.', education: 'LLB, University of Nairobi', barAdmission: 'Advocate of the High Court of Kenya', languages: 'English, Kiswahili, Somali', focusAreas: 'Dispute Resolution, Employment Law', email: 'info@harryadvocates.co.ke', sortOrder: 4 },
]

export const insightSeed = [
  { slug: 'understanding-kenyas-data-protection-act-for-businesses', title: "Understanding Kenya's Data Protection Act for Businesses", category: 'Corporate & Commercial', excerpt: 'What businesses handling customer data need to know about registration, consent and cross-border transfer obligations under the Data Protection Act, 2019.', content: 'Full article coming soon.', imageUrl: 'https://images.pexels.com/photos/33935830/pexels-photo-33935830.jpeg?auto=compress&cs=tinysrgb&w=700', readMinutes: 5 },
  { slug: 'mpesa-mobile-money-and-the-law', title: 'M-Pesa, Mobile Money and the Law: What Businesses Need to Know', category: 'Corporate & Commercial', excerpt: 'As mobile money becomes central to how Kenyan businesses get paid, we look at the legal considerations around Daraja API integrations and payment agreements.', content: 'Full article coming soon.', imageUrl: 'https://images.pexels.com/photos/5784803/pexels-photo-5784803.jpeg?auto=compress&cs=tinysrgb&w=700', readMinutes: 4 },
  { slug: 'succession-planning-why-every-family-needs-a-will', title: 'Succession Planning: Why Every Family Needs a Will', category: 'Family & Succession', excerpt: "Dying without a valid will can leave a family's affairs unsettled for years. Here is what a properly drafted will should cover.", content: 'Full article coming soon.', imageUrl: 'https://images.pexels.com/photos/8441773/pexels-photo-8441773.jpeg?auto=compress&cs=tinysrgb&w=700', readMinutes: 6 },
  { slug: 'understanding-your-rights-under-the-employment-act', title: 'Understanding Your Rights Under the Employment Act', category: 'Employment & Labour', excerpt: 'A practical overview of notice periods, termination procedures and dispute resolution options for employees and employers alike.', content: 'Full article coming soon.', imageUrl: 'https://images.pexels.com/photos/7495644/pexels-photo-7495644.jpeg?auto=compress&cs=tinysrgb&w=700', readMinutes: 5 },
]

export const testimonialSeed = [
  { quote: 'Harry Advocates guided us through a complex commercial dispute with clarity and confidence. Their advice was always practical, never just theoretical.', authorName: 'David Mwangi', authorRole: 'Managing Director, Mwangi & Sons Logistics', photoUrl: 'https://images.pexels.com/photos/32012999/pexels-photo-32012999.jpeg?auto=compress&cs=tinysrgb&w=300', sortOrder: 1 },
  { quote: 'When my father passed away, the succession process felt overwhelming. The team walked us through every step with patience and genuine care.', authorName: 'Susan Achieng', authorRole: 'Private Client', photoUrl: 'https://images.pexels.com/photos/20209020/pexels-photo-20209020.jpeg?auto=compress&cs=tinysrgb&w=300', sortOrder: 2 },
  { quote: 'Their corporate team handled our company restructuring efficiently and kept us informed at every stage.', authorName: 'Peter Kamau', authorRole: 'CEO, Kamau Construction Ltd', photoUrl: 'https://images.pexels.com/photos/18642680/pexels-photo-18642680.jpeg?auto=compress&cs=tinysrgb&w=300', sortOrder: 3 },
  { quote: 'We rely on Harry Advocates for all our employment law matters. Their advice is always clear, timely and commercially sensible.', authorName: 'Fatuma Ali', authorRole: 'HR Director, Coastline Retail Group', photoUrl: 'https://images.pexels.com/photos/10375968/pexels-photo-10375968.jpeg?auto=compress&cs=tinysrgb&w=300', sortOrder: 4 },
]
